### ISSUE TITLE
Date time parse error

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group1#81]
While testing the communication with your server (`developmentit3`, ) I observed the following error: 
### The Error (with stacktrace)

```
java.text.ParseException: Unparseable date: "1466925880"
        at java.text.DateFormat.parse(Unknown Source)
        at gse1.buergerbusserver.linemanagement.service.impl.rest.LinemanagementRestServiceImpl.newCustomStop(LinemanagementRestServiceImpl.java:188)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
...
```
### The Request:

``` JSON
{
 "info":{
    "userAddress":"Musterstrasse 5",
    "userName":"MaxMustermann"
  },
 "lineId":1,
 "deviceID":"random",
 "pickUpTime":1466925880,
 "numberOfPersons":1,
 "location":{
   "type":"Point",
   "coordinates":[0,0]
 }
}
```

The `pickUpTime` seems to be a valid unix time (at least according to [unix time converter](http://www.unixtime.de/) ).

**Comment by mbaniasad** [comment]
checking

**Comment by mbaniasad** [comment]
I have tried this and it worked

```
        {
         "info":{
            "userAddress":"Musterstrasse 5",
            "userName":"MaxMustermann",
            "assistance":[1,2,3]
          },
         "lineId":1,
         "deviceId":"random",
         "pickUpTime":1466925880,
         "numberOfPersons":1,
         "location":{
           "type":"Point",
           "coordinates":[111,220]
         }
        }
```

**Comment by mbaniasad** [comment]
@themetalone .. code still not complete the object is not being saved.
working on it again

**Comment by mbaniasad** [comment]
@themetalone my bad. code is correct just keep in mind for testing use a pickup time in future. or else you would not be able to see it in when requesting to see the custom stops

**Comment by themetalone** [comment]
So... is the error in my side? Did I use an old version of your server? Is the passed data wrong?

**Comment by themetalone** [comment]
Using Postman and the data you provided here I made a http post with header key: 
`Content-Type` `application/json` and I still get with your CI server

``` JSON
{
  "code": "TechnicalError",
  "message": "An unexpected error has occurred! We apologize any inconvenience. Please try again later.",
  "uuid": "2a5b54e5-8a9e-4aa3-9123-14e98666b7c3"
}
```

**Comment by Sriramk88** [comment]
@themetalone could you try with the recent server version and let us know if you still face any issues

{
         "info":{
            "address":"Musterstrasse 5",
            "name":"MaxMustermann",
            "assistance":[1,2,3]
          },
         "lineId":1,
         "deviceId":"random",
         "pickUpTime":1467024409,
         "numberOfPersons":1,
         "location":{
           "type":"Point",
           "coordinates":[111,220]
         }
        }

**Comment by themetalone** [comment]
Well... now I've got 

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
        at gse1.buergerbusserver.linemanagement.service.impl.rest.LinemanagementRestServiceImpl.newCustomStop(LinemanagementRestServiceImpl.java:196) ~[buergerbusserver-core-0.1-SNAPSHOT.jar!/:na]
```

**Comment by Sriramk88** [comment]
can you try a decimal value for coordinates instead of an integer

"location":{
"type":"Point",
"coordinates":[111.0,220.0]
}

**Comment by themetalone** [comment]
yields 

```
java.lang.NullPointerException: null
        at gse1.buergerbusserver.linemanagement.service.impl.rest.LinemanagementRestServiceImpl.newCustomStop(LinemanagementRestServiceImpl.java:205) ~[buergerbusserver-core-0.1-SNAPSHOT.jar!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_74]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_74]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180) ~[cxf-core-3.1.4.jar!/:3.1.4]
```

**Comment by Sriramk88** [comment]
could you copy here the content you are sending

**Comment by mbaniasad** [comment]
@Sriramk88  the error that is @themetalone is getting, I THINK is because of using "deviceId" instead Of "deviceID".
I would suggest both of you stick to [the interface document ](https://github.com/GSE-Project/SS2016-group1/wiki/Server-interfaces)and use what ever is there which is  "deviceID"
